baseURL = '/minutes'
relativeURLs = true
canonifyURLs = false
languageCode = 'en-us'
title = 'CCaWMU Meeting Minutes'
theme = 'minutes-theme'

[pagination]
  pagerSize = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Meeting minutes archive for the CCaWMU organization"
  clubName = "CCaWMU"
