baseURL = "/minutes/"
relativeURLs = true
canonifyURLs = false
languageCode = "en-us"
title = "CCaWMU Meeting Minutes"
theme = "minutes-theme"
paginate = 20
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
