# Site
name: CCaWMU
title: Computer Club at Western Michigan University
email: "rso_cclub@wmich.edu"
description: "The Computer Club at Western Michigan University."
baseurl: ""
url: "https://cclub.cs.wmich.edu/"
navigation:
    - text: Join
      url: /membership/
    - text: Guide
      url: /guide/
    - text: Chat
      url: https://cclub.cs.wmich.edu/chat
    - text: Wiki
      url: /wiki/
    - text: Minutes
      url: /minutes/
    - text: Hackathon
      url: /hackathon/

keep_files: [minutes/agenda.html, bounty/bounty.html]

# Build
markdown: kramdown
highligher: pygments
