# Site
name: CCoWMU
title: Computer Club of Western Michigan University
email: "cclub@yakko.cs.wmich.edu"
description: "The computer club of western michigan university."
baseurl: ""
url: "http://ccowmu.org/"
navigation:
    - text: Planet
      url: /planet/
    - text: Minutes
      url: /minutes/
    - text: Join
      url: /membership/
    - text: Projects
      url: /projects/
    - text: Events
      url: /events/
    - text: Wiki
      url: /wiki/
    - text: Plan
      url: http://whatistheplan.com/
    - text: More
      url: '#'
      drop:
        - text: Bounty
          url: '#'
        - text: Youtube
          url: https://www.youtube.com/user/wmucclub
        - text: Resources
        - text: Affiliates

keep_files: [minutes/agenda.html]

# Build
markdown: redcarpet
highligher: pygments
