# Site
name: CCoWMU
title: Computer Club of Western Michigan University
email: "rso_cclub@wmich.edu"
description: "The computer club of western michigan university."
baseurl: ""
url: "http://ccowmu.org/"
navigation:
    - text: Minutes
      url: /minutes/
    - text: Planet
      url: /planet/
    - text: Join
      url: /membership/
#    - text: Members
#      url: /members/
    - text: Events
      url: /events/
    - text: Talks
      url: /talks/
    - text: Wiki
      url: /wiki/
    - text: Sponsor
      url: /sponsors/
    - text: PLAN
      url: http://whatistheplan.com/

keep_files: [minutes/agenda.html, bounty/bounty.html]

# Build
markdown: redcarpet
highligher: pygments
