# Site
name: CCaWMU
title: Computer Club at Western Michigan University
email: "rso-computerclub@wmich.edu"
description: "The Computer Club at Western Michigan University."
baseurl: ""
url: "https://cclub.cs.wmich.edu/"
navigation:
    - text: Chat
      url: https://cclub.cs.wmich.edu/riot
    - text: Wiki
      url: /wiki/
    - text: Minutes
      url: /minutes/
    - text: Planet
      url: /planet/
    - text: Join
      url: /membership/
    - text: Events
      url: /events/

keep_files: [minutes/agenda.html, bounty/bounty.html]

# Build
markdown: redcarpet
highligher: pygments
