# Site
name: CCoWMU
title: Computer Club of Western Michigan University
email: "rso-computerclub@wmich.edu"
description: "The computer club of western michigan university."
baseurl: ""
url: "http://ccowmu.org/"
navigation:
    - text: Office
      url: /office/
    - text: Chat
      url: https://cclub.cs.wmich.edu/riot
    - text: Wiki
      url: /wiki/
    - text: Minutes
      url: /minutes/
    - text: Planet
      url: /planet/
    - text: Join
      url: /membership/
    - text: Gitlab
      url: https://dot.cs.wmich.edu
    - text: Events
      url: /events/
    - text: Sponsor
      url: /sponsors/
    - text: PLAN
      url: http://whatistheplan.com/

keep_files: [minutes/agenda.html, bounty/bounty.html]

# Build
markdown: redcarpet
highligher: pygments
