# Site
name: CCoWMU
title: Computer Club of Western Michigan University
email: "cclub@yakko.cs.wmich.edu"
description: "The computer club of western michigan university."
baseurl: ""
url: "http://ccowmu.org/"
navigation:
    - text: Planet
      url: /planet/
    - text: Minutes
      url: /minutes/
    - text: Officers
      url: /officers/
    - text: Join
      url: /membership/
    - text: Bounty
      url: /bounty/
    - text: Projects
      url: /projects/
    - text: Events
      url: /events/
    - text: Talks
      url: /talks/
    - text: Wiki
      url: /wiki/
    - text: Plan
      url: http://whatistheplan.com/

keep_files: [minutes/agenda.html, bounty/bounty.html]

# Build
markdown: redcarpet
highligher: pygments
