baseURL = "https://cclub.cs.wmich.edu/"
languageCode = "en-us"
title = "CCAWMU"
relativeURLs = false
canonifyURLs = true
enableRobotsTXT = true
ignoreErrors = ["error-disable-taxonomy"]

[params]
	description = "WMU's Resident Hackerspace Since 1976."
	underConstruction = true
