baseURL = "https://ccawmu.org/"
languageCode = "en-us"
title = "CCAWMU"

[params]
  description = "CCAWMU MINUTES"
  
[menu]
  [[menu.main]]
    identifier = "minutes"
    name = "Minutes"
    url = "/minutes/"
    weight = -110
