baseURL = "https://ccowmu.org"
languageCode = "en-us"
title = "Computer Club @ WMU Minutes"
theme = "ccowmu-minutes"

# Prevent Jekyll processing on GitHub Pages
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true
    codeFences = true

# Output formats
[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

# Custom output format for search index
[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "search"
    isPlainText = true
    notAlternative = true

# Site parameters
[params]
  description = "Meeting minutes for Western Michigan University's Computer Club"
  author = "Computer Club @ WMU"
  siteName = "CCaWMU Minutes"
  mainSiteURL = "https://ccowmu.org"
  
  # Performance settings
  enableSearchIndex = true
  enableRSS = true
  
  # UI settings
  defaultView = "grid"
  itemsPerPage = 50
  
# Menu configuration
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
    
  [[menu.main]]
    name = "All Minutes"
    url = "/minutes/"
    weight = 20
    
  [[menu.main]]
    name = "Back to Main Site"
    url = "https://ccowmu.org"
    weight = 30

# Build settings
[build]
  writeStats = true

# Security
[security]
  [security.funcs]
    getenv = ["^HUGO_", "^CI$"]
