baseURL = "https://cclub.cs.wmich.edu/minutes/"
relativeURLs = false
canonifyURLs = true
disableKinds = ["term", "RSS", "sitemap"]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[permalinks]
  minutes = "/:filename/"
[outputs]
home = ["HTML", "JSON"]

[params]
  underConstruction = true
