name: Hugo Site CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 6 * * *' # Runs every day at 6 AM
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Checkout minutes repo
        uses: actions/checkout@v4
        with:
          repository: ccowmu/minutes
          path: minutes-temp

      - name: Process minutes files
        run: |
          mkdir -p content/minutes
          for file in minutes-temp/*.md; do
            if [ -f "$file" ]; then
              filename=$(basename "$file" .md)
              # Extract date from filename (assuming YYYYMMDD format)
              if [[ $filename =~ ^([0-9]{4})([0-9]{2})([0-9]{2})$ ]]; then
                year=${BASH_REMATCH[1]}
                month=${BASH_REMATCH[2]}
                day=${BASH_REMATCH[3]}
                date="$year-$month-$day"
                title="Meeting Minutes - $month/$day/$year"
              else
                date=$(date -I)
                title="Meeting Minutes - $filename"
              fi
              
              # Create new file with front matter
              cat > "content/minutes/$filename.md" << EOF
          ---
          title: "$title"
          date: $date
          draft: false
          ---
          
          EOF
              # Append original content
              cat "$file" >> "content/minutes/$filename.md"
            fi
          done

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
